#!/usr/bin/env python3
"""Generate the Mimas 3/4-player compact HUD band (160x16) + layout.

3/4-player split-screen gives each quadrant a 160-wide, 16-tall OPAQUE HUD band
at the bottom of its 3D view.  The view shrinks 160x112 -> 160x96 (~14% fewer
pixels rendered per quadrant -> reclaimed perf) and the band, being opaque in the
NBG1 framebuffer, occludes the VDP1 wall layer below it (index 0 = VDP1 shows
through -- so the band bg MUST be non-zero).

The band itself is an authentic STBAR-derived dark bar (plain column x=51, top +
bottom bevel).  The per-player widgets (ready ammo, health%, armor%, and either
the keys held or -- in deathmatch -- the frag count) are drawn ON TOP by the core
(st_stuff.c ST_DrawQuadHud) using the small STYSNUM font + STKEYS icons + the
message-font '%' glyph.

Emits:
  - core/hud4p_layout.h      : band size + block-relative field anchors
  - src/hud4p_panel.h        : the 16-entry bevel column (memset per row)
  - tools/hud4p_preview.png  : RGB preview (x6) with sample widgets, both quadrant
                               columns, so the layout can be eyeballed before build
"""
import struct, zlib

WAD = "cd/data/DOOM1.WAD"
data = open(WAD, "rb").read()
_, numl, diroff = struct.unpack_from("<4sii", data, 0)
lumps = {}
for i in range(numl):
    off, sz, name = struct.unpack_from("<ii8s", data, diroff + i*16)
    lumps[name.rstrip(b"\0").decode("ascii", "replace")] = (off, sz)

def playpal0():
    off, _ = lumps["PLAYPAL"]
    return [tuple(data[off+i*3:off+i*3+3]) for i in range(256)]

def decode_patch(name):
    """-> (w, h, leftoff, topoff, img[h][w]) with None for transparent."""
    off, _ = lumps[name]
    w, h, lo, to = struct.unpack_from("<hhhh", data, off)
    colofs = struct.unpack_from("<%di" % w, data, off+8)
    img = [[None]*w for _ in range(h)]
    for x in range(w):
        p = off + colofs[x]
        while True:
            top = data[p]; p += 1
            if top == 0xFF: break
            cnt = data[p]; p += 2
            for k in range(cnt):
                y = top + k
                if 0 <= y < h: img[y][x] = data[p]
                p += 1
            p += 1
    return w, h, lo, to, img

PAL = playpal0()
_, _, _, _, STBAR = decode_patch("STBAR")

W, H = 160, 16

# ---- authentic dark bar: STBAR plain column x=51, bevelled to 16 px ----
# top bevel = STBAR rows 0..1, bottom bevel = STBAR rows 30..31, bg = STBAR row 15.
col = [STBAR[y][51] for y in range(32)]
bg  = col[15] if col[15] is not None else 51
column = [(v if v is not None else bg) for v in
          ([col[0], col[1]] + [col[15]]*12 + [col[30], col[31]])]
assert len(column) == H
assert all(v != 0 for v in column), \
    "band bg must be non-zero (index 0 = VDP1 shows through the band): %r" % column

# ---- field anchors (block-relative; the platform adds the quadrant origin) ----
# Numbers are RIGHT edges (STYSNUM small font ~4x6); '%' is drawn at the number x
# (its left edge), i.e. immediately right of the digits -- as hud2p_percent does.
NY = 5           # 6px-tall number centred in the 16px band
KY = 5           # 5px-tall key icon
fields = [
 ("AMMO",   32,  NY, "ready-weapon ammo right-edge (short nums; blank if no-ammo weapon)"),
 ("HEALTH", 72,  NY, "health right-edge; '%' drawn at this x"),
 ("ARMOR",  112, NY, "armor right-edge; '%' drawn at this x"),
 ("KEYS",   126, KY, "1st key icon left-edge (7x5); + KEYS_DX per icon (co-op)"),
 ("FRAGS",  152, NY, "deathmatch frag count right-edge (short nums)"),
]
KEYS_DX = 9

def emit_layout(path):
    with open(path, "w", newline="\n") as f:
        f.write("/* GENERATED by tools/make_hud4p.py -- DO NOT EDIT BY HAND.\n")
        f.write("   3/4-player compact HUD band: size + BLOCK-RELATIVE field anchors, shared by\n")
        f.write("   the band background (src/hud4p_panel.h) and the core per-player widget draw\n")
        f.write("   (st_stuff.c:ST_DrawQuadHud).  Band = bottom 16 px of each 160x112 quadrant;\n")
        f.write("   the 3D view above it is 160x96.  Number anchors are RIGHT edges. */\n")
        f.write("#ifndef HUD4P_LAYOUT_H\n#define HUD4P_LAYOUT_H\n\n")
        f.write("#define HUD4P_W %d\n" % W)
        f.write("#define HUD4P_H %d\n" % H)
        f.write("#define HUD4P_QUAD_H 112  /* SCREENHEIGHT/2: quadrant height (view + band) */\n")
        f.write("#define HUD4P_KEYS_DX %d\n\n" % KEYS_DX)
        for n, a, b, cm in fields:
            f.write("#define HUD4P_%s_X %3d  /* %s */\n#define HUD4P_%s_Y %3d\n" % (n, a, cm, n, b))
        f.write("\n#endif /* HUD4P_LAYOUT_H */\n")
    print("wrote", path)

def emit_panel(path):
    with open(path, "w", newline="\n") as f:
        f.write("/* GENERATED by tools/make_hud4p.py -- DO NOT EDIT BY HAND.\n")
        f.write("   3/4-player compact HUD band background: the 16-entry bevel column (authentic\n")
        f.write("   STBAR plain-column indices).  Each band row is a solid colour, so the platform\n")
        f.write("   paints it with one memset per row (dg_saturn.cxx:hud4p_blit_band). */\n")
        f.write("#ifndef HUD4P_PANEL_H\n#define HUD4P_PANEL_H\n")
        f.write('#include "hud4p_layout.h"\n\n')
        f.write("static const unsigned char hud4p_col[HUD4P_H] = {\n  ")
        f.write(",".join("%3d" % v for v in column))
        f.write("\n};\n\n#endif /* HUD4P_PANEL_H */\n")
    print("wrote", path)

# --------- preview: render the band with sample widgets (both quadrants) ---------
SHORT = [decode_patch("STYSNUM%d" % i) for i in range(10)]
KEYS  = [decode_patch("STKEYS%d" % i) for i in range(3)]
PCT   = decode_patch("STCFN037")   # '%' in the message font

def blit_patch(pan, patch, x, y):
    w, h, lo, to, img = patch
    for py in range(h):
        for px in range(w):
            v = img[py][px]
            if v is None: continue
            tx, ty = x - lo + px, y - to + py
            if 0 <= tx < W and 0 <= ty < H:
                pan[ty][tx] = v

def num_r(pan, x, y, num, font):   # right-justified (matches core hud2p_num)
    if num < 0: num = 0
    while True:
        d = num % 10
        w = font[d][0]
        x -= w
        blit_patch(pan, font[d], x, y)
        num //= 10
        if num == 0: break

def draw_widgets(pan, ammo, health, armor, cards, frags, dm):
    if ammo is not None:
        num_r(pan, fields[0][1], NY, ammo, SHORT)
    blit_patch(pan, PCT, fields[1][1], NY); num_r(pan, fields[1][1], NY, health, SHORT)
    blit_patch(pan, PCT, fields[2][1], NY); num_r(pan, fields[2][1], NY, armor,  SHORT)
    if dm:
        num_r(pan, fields[4][1], NY, frags, SHORT)
    else:
        for i in range(3):
            if cards[i] is not None:
                blit_patch(pan, KEYS[cards[i]], fields[3][1] + i*KEYS_DX, KY)

def emit_png(path, s=6):
    # two stacked sample rows: co-op (keys) then deathmatch (frags)
    samples = [
        dict(ammo=50,  health=100, armor=0,   cards=[0, 2, None], frags=0,  dm=False),
        dict(ammo=200, health=8,   armor=100, cards=[None]*3,     frags=17, dm=True),
    ]
    rows = []
    for smp in samples:
        pan = [[column[y]]*W for y in range(H)]
        draw_widgets(pan, **smp)
        rows.append(pan)
    gap = 4
    PH = H*len(rows) + gap*(len(rows)-1)
    raw = bytearray()
    for ri, pan in enumerate(rows):
        for y in range(H):
            for _ in range(s):
                raw.append(0)
                for x in range(W):
                    r, g, b = PAL[pan[y][x]]; raw.extend(bytes([r, g, b])*s)
        if ri != len(rows)-1:
            for _ in range(gap*s):
                raw.append(0); raw.extend(b"\x00\x00\x00"*(W*s))
    def chunk(t, q): return struct.pack(">I", len(q))+t+q+struct.pack(">I", zlib.crc32(t+q) & 0xffffffff)
    png = (b"\x89PNG\r\n\x1a\n"
           + chunk(b"IHDR", struct.pack(">IIBBBBB", W*s, PH*s, 8, 2, 0, 0, 0))
           + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
           + chunk(b"IEND", b""))
    open(path, "wb").write(png); print("wrote", path, "(%dx%d)" % (W*s, PH*s))

print("bevel column (top..bot):", column)
emit_layout("core/hud4p_layout.h")
emit_panel("src/hud4p_panel.h")
emit_png("tools/hud4p_preview.png", 6)
