#!/usr/bin/env python3
"""Generate the DoomSRL 2-player compact HUD panel (160x64) by RECOMPOSING the
original STBAR -- authentic wells + engraved labels, MOVED into two rows.

Framing uses STBAR's OWN pixels (plain column x=51 tiled), never synthetic
colours, so nothing clashes.  Every element -- incl. the engraved BULL/SHEL/
RCKT/CELL ammo-type labels + cur/max wells -- is MOVED from STBAR verbatim
(the labels already exist in the bar; no font rendering).

Reads STBAR/STARMS/PLAYPAL from cd/data/DOOM1.WAD and emits:
  - src/hud2p_panel.h        : 8bpp PLAYPAL-index array + field-anchor #defines
  - tools/hud2p_preview.png  : RGB preview (x4)
"""
import struct, zlib, collections

WAD = "cd/data/DOOM1.WAD"
data = open(WAD, "rb").read()
_, numl, diroff = struct.unpack_from("<4sii", data, 0)
lumps = {}
for i in range(numl):
    off, sz, name = struct.unpack_from("<ii8s", data, diroff + i*16)
    lumps[name.rstrip(b"\0").decode("ascii","replace")] = (off, sz)

def playpal0():
    off, _ = lumps["PLAYPAL"]
    return [tuple(data[off+i*3:off+i*3+3]) for i in range(256)]

def decode_patch(name):
    off, _ = lumps[name]
    w, h, lo, to = struct.unpack_from("<hhhh", data, off)
    colofs = struct.unpack_from("<%di" % w, data, off+8)
    img = [[None]*w for _ in range(h)]
    for x in range(w):
        p = off + colofs[x]
        while True:
            top = data[p]; p += 1
            if top == 0xFF: break
            cnt = data[p]; p += 2
            for k in range(cnt):
                y = top + k
                if 0 <= y < h: img[y][x] = data[p]
                p += 1
            p += 1
    return w, h, img

PAL = playpal0()

bw, bh, STBAR  = decode_patch("STBAR")
aw, ah, STARMS = decode_patch("STARMS")

# ---- authentic plain column (x=51): top bevel / bg / bottom bevel ----
PLAINCOL = [STBAR[y][51] for y in range(32)]

W, H, ROW = 160, 64, 32
pan = [[0]*W for _ in range(H)]

# base: tile the authentic plain column over BOTH rows (no synthetic bevels)
for x in range(W):
    for y in range(ROW):
        pan[y][x]        = PLAINCOL[y]
        pan[ROW + y][x]  = PLAINCOL[y]

def blit(src, sx0, sx1, dx, dy):
    for x in range(sx0, sx1):
        for y in range(len(src)):
            v = src[y][x]
            tx, ty = dx + (x - sx0), dy + y
            if v is not None and 0 <= tx < W and 0 <= ty < H:
                pan[ty][tx] = v

# ---- LINE 1 : AMMO+HEALTH+ARMS = STBAR[0..143] verbatim + ARMS grid ----
blit(STBAR, 0, 144, 0, 0)
for x in range(aw):
    for y in range(ah):
        v = STARMS[y][x]
        if v is not None and 104+x < 144: pan[y][104+x] = v
# cards: MOVE the authentic STBAR key-well strip (3 stacked wells, ~x236..252)
blit(STBAR, 236, 252, 144, 0)      # -> dst 144..159

# ---- LINE 2 : FACE | ARMOR | per-weapon ammo block ----
blit(STBAR, 143, 178, 0,  ROW)     # face recess          -> dst 0..34
blit(STBAR, 178, 235, 35, ROW)     # ARMOR label+well     -> dst 35..91
# per-weapon ammo: MOVE the authentic STBAR block (engraved BULL/SHEL/RCKT/CELL
# labels + the cur/max number wells) verbatim -- no font rendering.
ASRC, AEND = 254, 317               # full ammo content: "BULL" left edge .. max-well right
ADST = 97                            # centred in the [96..159] space, full labels (no clip)
blit(STBAR, ASRC, AEND, ADST, ROW) # -> dst 97..159
# authentic vertical divider (STBAR's AMMO|HEALTH groove: dark + light), in the gap
# between the ARMOR % (ends dst91) and the ammo labels (dst98)
blit(STBAR, 45, 49, 92, ROW)       # -> dst 92..95

# clean single divider: row 31 (line-1 bottom bevel, dark) stays; kill the bright
# top-bevel highlight that every line-2 section paints on row 32 -> set it to bg.
for x in range(W): pan[ROW][x] = PLAINCOL[15]

# ---- field anchors (block-relative; platform adds block origin) ----
NY1, NY2 = 3, ROW+3
fields = {
 "AMMO":   (44,  NY1,  "ready ammo right-edge (3 tall digits)"),
 "HEALTH": (90,  NY1,  "health right-edge; % drawn at this x"),
 "ARMS":   (111, 4,    "arms 2x3 grid (ST_ARMSX-rel: +12 x, +10 y per cell)"),
 "CARDS":  (147, 3,    "3 key icons (7x5) stacked, +10 y each"),
 "FACE":   (0,   ROW,  "face top-left (block-rel ST_FACESX=143->0; V_DrawPatch adds STFST offset)"),
 "ARMOR":  (78,  NY2,  "armor right-edge (% at this x)"),
 "AMMOCUR_X": (131, ROW+5, "per-weapon CURRENT ammo column right-edge (short nums)"),
 "AMMOMAX_X": (157, ROW+5, "per-weapon MAX ammo column right-edge (short nums)"),
 "AMMOROW0_Y":(ROW+5, 0,   "row 0 (BULL); pitch = 6px (rows at +0,+6,+12,+18)"),
}

def emit_layout(path):
    """core/hud2p_layout.h: panel size + BLOCK-RELATIVE field anchors, shared by the
       panel texture AND the core per-player widget draw (ST_DrawCompactWidgets)."""
    with open(path,"w",newline="\n") as f:
        f.write("/* GENERATED by tools/make_hud2p.py -- DO NOT EDIT BY HAND.\n")
        f.write("   2-player compact HUD layout: panel size + BLOCK-RELATIVE field anchors,\n")
        f.write("   shared by the panel texture (src/hud2p_panel.h) and the core per-player\n")
        f.write("   widget draw (st_stuff.c:ST_DrawCompactWidgets).  Block origins: P1=(0,160),\n")
        f.write("   P2=(160,160).  Number anchors are RIGHT edges; % drawn at the number x. */\n")
        f.write("#ifndef HUD2P_LAYOUT_H\n#define HUD2P_LAYOUT_H\n\n")
        f.write("#define HUD2P_W %d\n#define HUD2P_H %d\n#define HUD2P_ROW %d\n\n" % (160,64,ROW))
        for n,(a,b,cm) in fields.items():
            if n.endswith(("_X","_Y")):
                f.write("#define HUD2P_%s %3d  /* %s */\n" % (n, a, cm))
            else:
                f.write("#define HUD2P_%s_X %3d  /* %s */\n#define HUD2P_%s_Y %3d\n" % (n,a,cm,n,b))
        f.write("\n#endif /* HUD2P_LAYOUT_H */\n")
    print("wrote",path)

def emit_panel(path):
    """src/hud2p_panel.h: the 8bpp panel pixels; pulls anchors from hud2p_layout.h."""
    with open(path,"w",newline="\n") as f:
        f.write("/* GENERATED by tools/make_hud2p.py -- DO NOT EDIT BY HAND.\n")
        f.write("   2-player compact HUD panel (160x64, 8bpp PLAYPAL indices): the original STBAR\n")
        f.write("   wells/labels recomposed onto two rows.  Field anchors: see hud2p_layout.h. */\n")
        f.write("#ifndef HUD2P_PANEL_H\n#define HUD2P_PANEL_H\n")
        f.write('#include "hud2p_layout.h"\n\n')
        f.write("static const unsigned char hud2p_panel[HUD2P_W*HUD2P_H] = {\n")
        for y in range(64):
            f.write("  "+",".join("%3d"%pan[y][x] for x in range(160))+",\n")
        f.write("};\n\n#endif /* HUD2P_PANEL_H */\n")
    print("wrote",path)

def emit_png(path, p, s=4):
    raw=bytearray()
    for y in range(64):
        for _ in range(s):
            raw.append(0)
            for x in range(160):
                r,g,b=PAL[p[y][x]]; raw.extend(bytes([r,g,b])*s)
    def chunk(t,q): return struct.pack(">I",len(q))+t+q+struct.pack(">I",zlib.crc32(t+q)&0xffffffff)
    png=(b"\x89PNG\r\n\x1a\n"+chunk(b"IHDR",struct.pack(">IIBBBBB",160*s,64*s,8,2,0,0,0))
         +chunk(b"IDAT",zlib.compress(bytes(raw),9))+chunk(b"IEND",b""))
    open(path,"wb").write(png); print("wrote",path,"(%dx%d)"%(160*s,64*s))

print("PLAINCOL top=%d bg=%d bot=%d" % (PLAINCOL[0],PLAINCOL[15],PLAINCOL[31]))
emit_layout("core/hud2p_layout.h")
emit_panel("src/hud2p_panel.h")
emit_png("tools/hud2p_preview.png", pan, 4)
