/* GENERATED by tools/make_hud4p.py -- DO NOT EDIT BY HAND.
   3/4-player compact HUD band background: the 16-entry bevel column (authentic
   STBAR plain-column indices).  Each band row is a solid colour, so the platform
   paints it with one memset per row (dg_saturn.cxx:hud4p_blit_band). */
#ifndef HUD4P_PANEL_H
#define HUD4P_PANEL_H
#include "hud4p_layout.h"

static const unsigned char hud4p_col[HUD4P_H] = {
  100,105,105,105,105,105,105,105,105,105,105,105,105,105,105,108
};

#endif /* HUD4P_PANEL_H */
